# https://github.com/grafana/tempo/blob/main/example/docker-compose/otel-collector/otel-collector.yaml

receivers:
  # Initialise an OpenTelemetry receiver with default settings
  otlp:
    protocols:
      grpc:
      http:

exporters:
  # Configure an export 'otlp' where we want to send telemetry to
  otlp:
    endpoint: "${TEMPO_ENDPOINT}"
    headers:
      authorization: "Basic ${TEMPO_AUTH_STRING}"

service:
  pipelines:
    traces:
      receivers: [otlp] #[jaeger]
      exporters: [otlp]
